package:
    name: pyamg
    version: "3.0.2"

source:
    git_url: https://github.com/pyamg/pyamg.git
    git_tag: v3.0.2

build:
    number: 1

requirements:
    build:
        - python
        - numpy
        - scipy
        - nose
        - zlib  # [linux]
        - gcc # [osx]
    run:
        - python
        - numpy
        - scipy
        - zlib  # [linux]

test:
    requires:
        - nose
    imports:
        - pyamg

about:
    home: http://www.pyamg.org/
    license: MIT
    license_file: LICENSE.txt
