package:
    name: megaman
    version: 0.1.1

source:
    git_url: https://github.com/mmp2/megaman.git
    git_tag: v0.1.1

build:
    number: 1

requirements:
    build:
        - python
        - cython
        - numpy
        - flann
        - gcc [osx]
    run:
        - python
        - numpy
        - scipy
        - scikit-learn
        - pyamg
        - pyflann

test:
    requires:
        - nose
    imports:
        - megaman
        - megaman.geometry
        - megaman.embedding
        - megaman.utils

about:
    home: http://mmp2.github.io/megaman
    license: BSD
    license_file: LICENSE
